/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BackEnd.EventHandling;
import UserInterface.components.ImageGrid;
import java.awt.Color;
import java.awt.Graphics;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import jiconfont.icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author gauravpunjabi
 */
public class MainFrame extends javax.swing.JFrame {

    private ImageGrid imageGrid;
    private JScrollPane jsp;
    private EventHandling eventHandling;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        customInit();
    }
    private void customInit() {
        this.setSize(1210,800);
        this.eventHandling = new EventHandling(this);
        this.getContentPane().setBackground(Color.WHITE);
        IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());
        imageGrid = new ImageGrid();
        jsp = new JScrollPane(imageGrid);
        jsp.setBorder(null);
        this.jtfSearch.addActionListener(eventHandling);
        this.add(jsp, new AbsoluteConstraints(10, 100, 1200, 800));
        this.jlSearch.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SEARCH, 45, this.jlSearch.getForeground()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSearch = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                g.setColor(this.getForeground());
                g.drawRoundRect(0,0,this.getWidth(),this.getHeight(),25,25);
                super.paintComponent(g);
            }
        };
        jlSearch = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSearch.setForeground(new java.awt.Color(238, 238, 238));
        jpSearch.setOpaque(false);

        jlSearch.setForeground(new java.awt.Color(255, 255, 255));

        jtfSearch.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        jtfSearch.setForeground(new java.awt.Color(204, 204, 204));
        jtfSearch.setText("jTextField1");
        jtfSearch.setBorder(null);

        javax.swing.GroupLayout jpSearchLayout = new javax.swing.GroupLayout(jpSearch);
        jpSearch.setLayout(jpSearchLayout);
        jpSearchLayout.setHorizontalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSearchLayout.setVerticalGroup(
            jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 20, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    public void setImages(ArrayList<URL> images) {
        imageGrid.setImages(images);
    }
    public JTextField getSearchTextField() {
        return this.jtfSearch;
    }
    public JLabel getSearchLabel() {
        return this.jlSearch;
    }
    public JPanel getSearchPanel() {
        return this.jpSearch;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlSearch;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
