/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.components;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import net.coobird.thumbnailator.Thumbnails;

/**
 *
 * @author gauravpunjabi
 */
public class ImageGrid extends javax.swing.JPanel {

    /**
     * Creates new form ImageFrame
     */
    public ImageGrid() {
        initComponents();
        customInit();
    }

    private void customInit() {
        this.labels = new ArrayList<>();
        this.setLayout(null);
        for (int i = 10; i <= 790; i += 390) {
            for (int j = 10; j <= 790; j += 390) {
                Picture picture = new Picture();
                picture.setBounds(j, i, 380, 380);
                labels.add(picture);
                this.add(picture);
            }
        }
        this.revalidate();
        this.setPreferredSize(new Dimension(1610, 1200));
    }

    private class Picture extends JLabel {

        public Picture() {
            this.setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            g.setColor(Color.white);
            g.fillRoundRect(0, 0, this.getWidth(), this.getHeight(), 20, 20);
            super.paintComponent(g);
        }
    }

    public void setImages(ArrayList<URL> images) throws IllegalArgumentException {
        if (images.size() > 9) {
            throw new IllegalArgumentException("Too much images passed.");
        }
        removeAllIcons();
        for (int i = 0; i < images.size(); i++) {
            try {
                labels.get(i).setIcon(new ImageIcon(Thumbnails.of(ImageIO.read(images.get(i))).size(380, 380).asBufferedImage()));
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        }
    }
    private void removeAllIcons() {
        for(Picture picture : labels) {
            picture.setIcon(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String[] args)throws Exception {
        JFrame jf = new JFrame();
        jf.setSize(1200, 768);
        jf.setLayout(null);
        ImageGrid grid = new ImageGrid();
//        grid.setSize(1610,1180);
        JScrollPane jsp = new JScrollPane(grid);
        jsp.setBounds(0, 0, 1200, 768);
        jsp.setBorder(null);
        jf.add(jsp);
//        grid.setPreferredSize(new Dimension(1610,1200));
//        jsp.add(grid);
        jf.setVisible(true);
        ArrayList<URL> images = new ArrayList<>();
        images.add(new URL("https://images.unsplash.com/photo-1491193348662-47874a96c621?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=bec5be982f299e6ba8840b4ae9f80cfd&auto=format&fit=crop&w=1655&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1516203294340-5ba5f612dc6a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b79294f231ab4799218e82818a07de1&auto=format&fit=crop&w=1185&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1518481612222-68bbe828ecd1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=53417780c9a34ffae5334a1d03b105a6&auto=format&fit=crop&w=1650&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1485646485012-f09e6a19d9c4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=35deb3c9cdf9c401a71377fb09238eb4&auto=format&fit=crop&w=1650&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1485646485012-f09e6a19d9c4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=35deb3c9cdf9c401a71377fb09238eb4&auto=format&fit=crop&w=1650&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1485646485012-f09e6a19d9c4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=35deb3c9cdf9c401a71377fb09238eb4&auto=format&fit=crop&w=1650&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1516203294340-5ba5f612dc6a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b79294f231ab4799218e82818a07de1&auto=format&fit=crop&w=1185&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1516203294340-5ba5f612dc6a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b79294f231ab4799218e82818a07de1&auto=format&fit=crop&w=1185&q=80"));
        images.add(new URL("https://images.unsplash.com/photo-1516203294340-5ba5f612dc6a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b79294f231ab4799218e82818a07de1&auto=format&fit=crop&w=1185&q=80"));
        grid.setImages(images);
    }    
    private ArrayList<Picture> labels;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
